sudo: false
language: python
cache: pip

python:
  - "3.6"

script:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run flake8
  - pipenv run py.test --cov=./
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: $PyPiLogin
  password: $PyPiPassword
  on:
    tags: true
