sudo: false
language: python
cache: pip

python:
  - "3.5"

script:
  - flake8
  - py.test --cov=./
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: $PyPiLogin
  password: $PyPiPassword
  on:
    tags: true
